### PR TITLE
wow major merge

### PR DESCRIPTION
**Pull request by sckasturi**

### CODE REVIEW

**Comment by ghost** [comment]
Why are you using a pull request for this?

**Comment by ghost** [comment]
Also, I forgot I even have access to this repo.

**Comment by sckasturi** [comment]
i have no idea, too lazy to do it via git

–Srijay Kasturi
http://techfilmer.com

**Comment by ghost** [comment]
The proper way would be `git cherry-pick firstcommit..lastcommit` anyway, because merge commits caused by periodic merges from upstream are just clutter.

**Pull request closed without merging**
